In [1]:
import numpy as np

In [53]:
def rmse(pred, label):  # [5pts]
    return np.sqrt(np.sum((pred-label)**2)/len(pred))

In [72]:
xtrain = np. array([[-0.41976616, -1.39997687, -1.07323997,  1.86739216,  3.50107668,0.88718145],
                        [-0.41976616, -1.1957663 , -0.95071363,  0.7952867 ,  1.71423424,0.24391817],
                        [-0.41976616, -0.99155574, -0.82818729,  0.02949708,  0.43791821,-0.2155556 ],
                        [-0.41976616, -0.78734518, -0.70566095, -0.42997669, -0.32787141,-0.49123986],
                        [-0.41976616, -0.58313461, -0.58313461, -0.58313461, -0.58313461,-0.58313461],
                        [-0.41976616, -0.37892405, -0.46060827, -0.42997669, -0.32787141,-0.49123986],
                        [-0.41976616, -0.17471348, -0.33808193,  0.02949708,  0.43791821,-0.2155556 ],
                        [-0.41976616,  0.02949708, -0.2155556 ,  0.7952867 ,  1.71423424,0.24391817],
                        [-0.41976616,  0.23370765, -0.09302926,  1.86739216,  3.50107668,0.88718145]])
ytrain = np.array([[ 2.93151 ],
                [-0.16618882],
                [-0.41168219],
                [-1.27454902],
                [-1.55952313],
                [-1.39394503],
                [ 0.08333787],
                [ 2.24819231],
                [ 2.00011928]])
epochs = 5
learning_rate = 0.001

In [74]:
weight = np.zeros(len(xtrain[0]))
cost_history_list = []

for epoch in range(epochs):  # begin the process
    # compute the dot product between our feature 'X' and weight 'W'
    print(weight)
    y_pred = xtrain * weight
    # calculate the difference between the actual and predicted value 
    # calculate the cost (Mean squared error - MSE)
    cost = rmse(y_pred, ytrain)
    weight = weight + learning_rate/len(xtrain) * np.sum(np.dot(xtrain.T, ytrain-y_pred), axis=1)
    cost_history_list.append(cost)
print(np.array([weight]))
print(np.array(cost_history_list))

[0. 0. 0. 0. 0. 0.]
[-0.00068765 -0.00035787 -0.00059683  0.00860813  0.01498373  0.00478277]
[-0.00136627 -0.00070298 -0.001181    0.01717757  0.02989463  0.00954734]
[-0.00203591 -0.00103543 -0.00175257  0.02570852  0.04473305  0.01429381]
[-0.00269662 -0.00135528 -0.00231161  0.03420116  0.05949934  0.01902225]
[[-0.00334843 -0.0016626  -0.00285821  0.04265568  0.07419388  0.02373277]]
[3.98767377 3.9742827  3.96112629 3.94820346 3.93551306]


In [ ]:
linear_GD = np.array([[-0.00055807],
                    [-0.0002771 ],
                    [-0.00047637],
                    [ 0.00710928],
                    [ 0.01236565],
                    [ 0.00395546]])

linear_GD_loss = np.array([1.6224629259205612,
                            1.6169984564771551,
                            1.6115674174496362,
                            1.6061696355422785,
                            1.6008049381327374])