In [32]:
import numpy as np
import pickle

In [8]:
prob = 0.3
u = np.array([
    [ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788],
    [ 0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
    [ 0.76103773,  0.12167502,  0.44386323,  0.33367433,  1.49407907, -0.20515826],
    [ 0.3130677 , -0.85409574, -2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
    [ 2.26975462, -1.45436567,  0.04575852, -0.18718385,  1.53277921,  1.46935877]
])

In [9]:
np.random.seed(0)
u*np.random.binomial(1, 1-prob, size = u.shape)/(1-prob)


array([[ 2.52007479,  0.        ,  1.39819711,  3.201276  ,  2.66793999,
        -1.39611126],
       [ 1.35726917, -0.        , -0.        ,  0.58656929,  0.        ,
         2.07753359],
       [ 1.08719676,  0.        ,  0.63409033,  0.47667761,  2.13439867,
        -0.        ],
       [ 0.        , -0.        , -0.        ,  0.        ,  1.23490886,
        -0.        ],
       [ 3.2425066 , -2.07766524,  0.06536931, -0.        ,  2.18968459,
         2.09908396]])

In [38]:
param=pickle.load(open('local_tests/test_data/nn_param.pickle', 'rb'))
dLoss = pickle.load(open('local_tests/test_data/dLoss.pickle', 'rb'))
lr = 0.01

In [55]:
for layer in dLoss:
    print(layer)

theta1
b1
theta2
b2


In [53]:
test = param["theta1"] - lr * dLoss["theta1"]
theta1 == test  # IMPLEMENT THIS LINE

[[ 4.74002237e-09  2.80225282e-09 -5.53590507e-10]
 [ 3.77709430e-09 -1.74328507e-09  2.39757170e-09]
 [ 4.01079725e-09 -4.79819773e-09 -1.21315910e-09]
 [ 1.92281738e-09 -1.44554257e-09  2.07158246e-09]
 [-2.52736906e-09  1.36372941e-09  4.03970490e-09]]


array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [44]:
theta1 = np.array([
    [ 0.94882242, -0.36464497, -0.31395601],
    [-0.62450367,  0.49063477, -1.32195671],
    [ 1.00859644, -0.43012531,  0.18687619],
    [-0.14927761,  0.85106502, -1.18545526],
    [-0.17927593, -0.21328183,  0.66129455]
])
b1 = np.array([[0.00012665], [0.0111731], [-0.00234416], [-0.01659802], [-0.00742044]])

In [ ]:
param["b1"] - lr * dLoss["b1"]